

eureka:
  client:
    serviceUrl:
      defaultZone: http://annuaire:1111/eureka/
    healthcheck:
      enabled: true
    preferSameZoneEureka: true
  instance:
    metadataMap:
      zone: zone1
    

logging:
  level:
    root: INFO

